export default [
    {
        id:1,
        postedOn: '2023-10-23',
        title: 'iOS Developer',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["WwiftUI", "UiKit", "Core Data"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id:2,
        postedOn: '2023-10-24',
        title: 'Frontend Developer',
        type: 'Full Time',
        location: 'In-office',
        experience: 'Fresher',
        comapny: "Amazon",
        skills: ["Javascript", "NextJs", "CSS"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id:3,
        postedOn: '2023-11-02',
        title: 'Developer Advocate',
        type: 'Full Time',
        location: 'Hybrid',
        experience: 'Junior Level',
        comapny: "Netflix",
        skills: ["web3", "Content creation", "Community"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id:2,
        postedOn: '2023-10-12',
        title: 'Android Developer',
        type: 'Contract',
        location: 'In-office',
        experience: 'Fresher',
        comapny: "Facebook",
        skills: ["Kotlin", "MVVM"],
        job_link: "https://www.apple.com/careers/in/",
    },
]